# Generated by Django 4.1.6 on 2023-02-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cjkcms", "0005_layoutsettings_custom_font_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticssettings",
            name="cookie_consent",
            field=models.BooleanField(
                default=False,
                help_text="Enable simple GDPR compliant cookie consent banner. Intended as a quick solution for sites that don't need a fully customisable consent.",
                verbose_name="Enable cookie consent",
            ),
        ),
        migrations.AddField(
            model_name="analyticssettings",
            name="cookie_consent_deny_btn",
            field=models.BooleanField(
                default=False,
                help_text="Show a deny button in the cookie consent banner. If unchecked, the banner will only have an accept and settings buttons.",
                verbose_name="Show deny button",
            ),
        ),
    ]
