# Generated by Django 5.2.1 on 2025-11-15 23:07

import cjkcms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cjkcms', '0024_remove_cjkcmspage_struct_org_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmpanel',
            name='background_color',
            field=cjkcms.fields.ColorField(blank=True, max_length=255, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='filmpanel',
            name='foreground_color',
            field=cjkcms.fields.ColorField(blank=True, max_length=255, verbose_name='Text color'),
        ),
    ]
